const constants = {
    FETCH_ARTICLES_BEGIN: "FETCH_ARTICLES_BEGIN",
    FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
    FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",

    FETCH_ADMIN_ARTICLES_BEGIN: "FETCH_ADMIN_ARTICLES_BEGIN",
    FETCH_ADMIN_ARTICLES_SUCCESS: "FETCH_ADMIN_ARTICLES_SUCCESS",
    FETCH_ADMIN_ARTICLES_FAILURE: "FETCH_ADMIN_ARTICLES_FAILURE",

    ADD_ARCHIVE_BEGIN: "ADD_ARCHIVE_BEGIN",
    ADD_ARCHIVE_SUCCESS: "ADD_ARCHIVE_SUCCESS",
    ADD_ARCHIVE_FAILURE: "ADD_ARCHIVE_FAILURE",

    RESTORE_ARCHIVE_BEGIN: "RESTORE_ARCHIVE_BEGIN",
    RESTORE_ARCHIVE_SUCCESS: "RESTORE_ARCHIVE_SUCCESS",
    RESTORE_ARCHIVE_FAILURE: "RESTORE_ARCHIVE_FAILURE",

    DEL_ARTICLE_BEGIN: "DEL_ARTICLE_BEGIN",
    DEL_ARTICLE_SUCCESS: "DEL_ARTICLE_SUCCESS",
    DEL_ARTICLE_FAILURE: "DEL_ARTICLE_FAILURE",

    SELECT_ARTICLES: "SELECT_ARTICLES",
    ADD_SELECT_ARTICLES: "ADD_SELECT_ARTICLES",
    DEL_SELECT_ARTICLES: "DEL_SELECT_ARTICLES",
    CLEAR_SELECT_ARTICLES: "CLEAR_SELECT_ARTICLES",

    FETCH_ARTICLE_BEGIN: "FETCH_ARTICLE_BEGIN",
    FETCH_ARTICLE_SUCCESS: "FETCH_ARTICLE_SUCCESS",
    FETCH_ARTICLE_FAILURE: "FETCH_ARTICLE_FAILURE",


    EDIT_ARTICLE: "EDIT_ARTICLE",
    NEW_ARTICLE: "NEW_ARTICLE",
    SELECT_ARTICLE: "SELECT_ARTICLE",
    CLEAR_ARTICLE: "CLEAR_ARTICLE",

    EDIT_ARTICLE_BEGIN: "EDIT_ARTICLE_BEGIN",
    //--------------------------------------------
};

export default constants