const constants = {
    FETCH_ARTICLES_BEGIN: "FETCH_ARTICLES_BEGIN",
    FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
    FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",

    SELECT_ARTICLES: "SELECT_ARTICLES",
    ADD_SELECT_ARTICLES: "ADD_SELECT_ARTICLES",
    DEL_SELECT_ARTICLES: "DEL_SELECT_ARTICLES",
    CLEAR_SELECT_ARTICLES: "CLEAR_SELECT_ARTICLES",

    FETCH_ARTICLE_BEGIN: "FETCH_ARTICLE_BEGIN",
    FETCH_ARTICLE_SUCCESS: "FETCH_ARTICLE_SUCCESS",
    FETCH_ARTICLE_FAILURE: "FETCH_ARTICLE_FAILURE",


    SELECT_ARTICLE: "SELECT_ARTICLE",

    EDIT_ARTICLE_BEGIN: "EDIT_ARTICLE_BEGIN",
    //--------------------------------------------
};

export default constants