const constants = {
    FETCH_ARTICLES_BEGIN: "FETCH_ARTICLES_BEGIN",
    FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
    FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",

    //--------------------------------------------

    ON_LOGOUT: "ON_LOGOUT",
    ON_LOGIN: "ON_LOGIN",

    //Post List
    FETCH_POSTS : 'FETCH_POSTS',
    FETCH_POSTS_SUCCESS : 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE : 'FETCH_POSTS_FAILURE',
    RESET_POSTS : 'RESET_POSTS',




    ADD_ARTICLE: "ADD_ARTICLE",
    EDIT_ARTICLE: "EDIT_ARTICLE",
    DEL_ARTICLE: "DEL_ARTICLE",


    GETALL_REQUEST: 'ARTICLES_GETALL_REQUEST',
    GETALL_SUCCESS: 'ARTICLES_GETALL_SUCCESS',
    GETALL_FAILURE: 'ARTICLES_GETALL_FAILURE',

    ADD_USER: "ADD_USER",
    RATE_USER: "RATE_USER",
    REMOVE_USER: "REMOVE_USER",

    SORT_USERS: "SORT_USERS",

    SORT_COLORS: "SORT_COLORS",
    ADD_COLOR: "ADD_COLOR",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR"
};

export default constants